//! The mock source adapter the live journey runs against.
//!
//! The smallest complete source adapter: it reads a greeting fixture and asks
//! the model to describe it as claims. It exists so the engine can be
//! exercised end to end without depending on a first-party adapter from the
//! adapters repository.
//!
//! It has the shape of a real adapter — one `SourceAdapter` implementation, an
//! embedded prose tree, a single `source!` export — with one difference: a
//! root-package example has no build script of its own (the root's builds the
//! engine), so the document table is written by hand rather than generated by
//! `emery_sdk::registry!`.

emery_sdk::source!(crate::Adapter);

use std::future::{Future, ready};

use emery_sdk::{
    Context, Doc, Error, Model, Seam, SourceAdapter, SourceContent, SourceKind, bad_request,
};

static DOCS: &[Doc] = &[
    Doc {
        path: "prompts/extract.md",
        body: include_str!("prose/prompts/extract.md"),
    },
    Doc {
        path: "references/greeting.md",
        body: include_str!("prose/references/greeting.md"),
    },
];

/// The adapter over the greeting fixture.
#[derive(Debug)]
pub struct Adapter;

impl SourceAdapter for Adapter {
    const KIND: SourceKind = SourceKind::Documentation;

    fn docs() -> &'static [Doc] {
        DOCS
    }

    // One seam, chosen without the model — so the survey is ready at
    // once: an empty inline brief is refused, a non-empty one is bound, and
    // a workspace is pointed at `references/greeting.md` as the fallback when
    // the tree states no greeting.
    fn survey<P: Model>(
        _model: &P, ctx: &Context<'_>,
    ) -> impl Future<Output = Result<Vec<Seam>, Error>> + Send {
        let seam = match &ctx.input.content {
            SourceContent::Value(value) if value.trim().is_empty() => {
                return ready(Err(bad_request!("the bound greeting brief is empty")));
            }
            SourceContent::Value(_) => Seam::Whole,
            SourceContent::Workspace(root) => Seam::Note(format!(
                "`$SOURCE_DIR` is the read-only view at `{root}` — the greeting tree the prompt \
                 walks. Prefer the bound tree; fall back to `references/greeting.md` when the \
                 tree does not state a greeting. Nothing outside it is reachable; extract mines \
                 only this source."
            )),
        };
        ready(Ok(vec![seam]))
    }
}
