//! Mock source adapter
//!
//! The smallest complete source adapter: it reads a greeting fixture and
//! asks the model to describe it as claims. It exists so the engine can be
//! exercised end to end on the live journey without depending on a
//! first-party adapter from the adapters repository.
//!
//! It has the shape of a real adapter — one `SourceAdapter` implementation,
//! an embedded prose tree, a single `source!` export — with one difference: a
//! root-package example has no build script of its own (the root's builds the
//! engine), so the document table is written by hand rather than generated by
//! `emery_prose::registry!`.

emery_sdk::source!(crate::Adapter);

use emery_prose::registry::Doc;
use emery_sdk::{
    Context, Error, Evidence, Material, Model, SourceAdapter, SourceContent, bad_request,
};

static DOCS: &[Doc] = &[
    Doc {
        path: "prompts/extract.md",
        body: include_str!("prose/prompts/extract.md"),
    },
    Doc {
        path: "references/greeting.md",
        body: include_str!("prose/references/greeting.md"),
    },
];

/// Extracts the greeting fixture into structured claims.
#[derive(Debug)]
pub struct Adapter;

impl SourceAdapter for Adapter {
    const SOURCE: &'static str = "greeting";

    fn docs() -> &'static [Doc] {
        DOCS
    }

    async fn extract<P: Model>(model: &P, ctx: &Context<'_>) -> Result<Evidence, Error> {
        Self::evidence(model, ctx, material(ctx)?).await
    }
}

// Refuses an empty inline brief, binds a non-empty one, and points a
// workspace at `references/greeting.md` as the fallback when the tree states
// no greeting.
fn material(ctx: &Context<'_>) -> Result<Material, Error> {
    match &ctx.input.content {
        SourceContent::Value(value) if value.trim().is_empty() => {
            Err(bad_request!("the bound greeting brief is empty"))
        }
        SourceContent::Value(_) => Ok(Material::Bound),
        SourceContent::Workspace(root) => Ok(Material::Prepared(format!(
            "`$SOURCE_DIR` is the read-only view at `{root}` — the greeting tree the prompt \
             walks. Prefer the bound tree; fall back to `references/greeting.md` when the tree \
             does not state a greeting. Nothing outside it is reachable; extract mines only this \
             source."
        ))),
    }
}
