//! Build-time corpus embedding
//!
//! Walks a Markdown tree at build time and generates the document table the
//! [`crate::registry!`] macro includes, so a crate's prose is compiled in and
//! versioned with its code.
//!
//! Every relative link in the tree is checked while embedding. Prompts are
//! meant to reference depth rather than inline it, and a dangling reference
//! would otherwise only be discovered when a model asked for the document.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Result, bail};

// One Markdown document found in the tree: its tree-relative path and the
// canonical file the generated table `include_str!`s.
struct Markdown {
    path: String,
    file: PathBuf,
}

/// Embeds and link-checks the Markdown `tree` relative to the crate manifest,
/// writing `prose_docs.rs` into `OUT_DIR`.
///
/// # Panics
///
/// Panics on any failure so the build stops.
pub fn emit(tree: &str) {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));

    let root = manifest_dir.join(tree);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));

    if let Err(err) = emit_from(&root, &out_dir) {
        panic!("prose codegen failed for {}: {err:#}", root.display());
    }
}

// Walks `root` and writes a sorted `DOCS` table to `out_dir/prose_docs.rs`.
fn emit_from(root: &Path, out_dir: &Path) -> Result<()> {
    let mut files = Vec::new();
    if root.is_dir() {
        walk(root, "", &mut files, &mut Vec::new())?;
    }

    if files.is_empty() {
        bail!("no markdown documents found under {}", root.display());
    }

    files.sort_by(|a, b| a.path.cmp(&b.path));

    let mut code = String::from(
        "// @generated by prose — do not edit\n\
         \n\
         /// Every embedded prompt document, sorted by tree-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );

    for Markdown { path, file } in &files {
        check_links(file)?;

        writeln!(
            code,
            "    Doc {{ path: {path:?}, body: include_str!({file:?}) }},",
            file = file.display().to_string(),
        )?;
    }

    code.push_str("];\n");

    fs::write(out_dir.join("prose_docs.rs"), code)?;
    Ok(())
}

// Recurses into `dir`, collecting Markdown files. Symlinks are followed, so
// the canonical-path stack is the cycle guard.
fn walk(dir: &Path, path: &str, files: &mut Vec<Markdown>, stack: &mut Vec<PathBuf>) -> Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());

    let canonical = fs::canonicalize(dir)?;
    if stack.contains(&canonical) {
        bail!("symlink cycle: {} re-enters {}", dir.display(), canonical.display());
    }

    stack.push(canonical);
    let walked = walk_entries(dir, path, files, stack);
    stack.pop();
    walked
}

fn walk_entries(
    dir: &Path, path: &str, files: &mut Vec<Markdown>, stack: &mut Vec<PathBuf>,
) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let entry_path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let path = if path.is_empty() { name } else { format!("{path}/{name}") };

        let metadata = fs::metadata(&entry_path)?;
        if metadata.is_dir() {
            walk(&entry_path, &path, files, stack)?;
        } else if metadata.is_file() && entry_path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", entry_path.display());
            files.push(Markdown {
                path,
                file: fs::canonicalize(&entry_path)?,
            });
        }
    }

    Ok(())
}

// Fails on any relative link in `file` whose target does not exist. Fenced
// code is skipped so a `](` inside a snippet is not a link.
fn check_links(file: &Path) -> Result<()> {
    let body = fs::read_to_string(file)?;
    let dir = file.parent().expect("file");
    let mut in_fence = false;

    for line in body.lines() {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
            continue;
        }
        if in_fence {
            continue;
        }

        for target in link_targets(line) {
            let path = target.split('#').next().unwrap_or_default();
            if path.is_empty() || target.contains("://") || target.starts_with("mailto:") {
                continue;
            }

            let path = dir.join(path);
            if !path.exists() {
                bail!(
                    "{}: broken link `{target}` ({} does not exist)",
                    file.display(),
                    path.display()
                );
            }
        }
    }

    Ok(())
}

fn link_targets(mut body: &str) -> impl Iterator<Item = &str> {
    std::iter::from_fn(move || {
        let open = body.find("](")?;
        body = &body[open + 2..];
        let close = body.find(')')?;
        let target = body[..close].trim();
        body = &body[close + 1..];
        Some(target)
    })
}

#[cfg(test)]
mod tests {
    use std::os::unix::fs::symlink;

    use super::*;

    // A directory symlink is followed and a `](` inside fenced code is not a
    // link; the live engine tree has neither, so this is the only coverage.
    #[test]
    fn embeds() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let shared = tmp.path().join("shared");
        write(&shared, "rule.md", "# Rule\n");
        let tree = tmp.path().join("prompts");
        write(&tree, "a.md", "see [b](b.md)\n\n```swift\nprocessEffects([UInt8](effects))\n```\n");
        write(&tree, "b.md", "# B\n");
        let _ = symlink(&shared, tree.join("runtime"));
        let out = tmp.path().join("out");
        fs::create_dir_all(&out).expect("mkdir out");

        emit_from(&tree, &out).expect("emit");
        let generated = fs::read_to_string(out.join("prose_docs.rs")).expect("generated");
        assert!(generated.contains("path: \"a.md\""), "{generated}");
        assert!(generated.contains("path: \"b.md\""), "{generated}");
        assert!(generated.contains("path: \"runtime/rule.md\""), "{generated}");
    }

    // A dangling link and a symlink cycle each fail the build; no live corpus
    // can arrange either.
    #[test]
    fn refuses() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let out = tmp.path().join("out");
        fs::create_dir_all(&out).expect("mkdir");

        let dangling = tmp.path().join("dangling");
        write(&dangling, "a.md", "see [missing](nope.md)\n");
        let err = emit_from(&dangling, &out).expect_err("dangling");
        assert!(err.to_string().contains("nope.md"), "{err}");

        let cycle = tmp.path().join("cycle");
        write(&cycle, "intro.md", "# Intro\n");
        let _ = symlink(Path::new("."), cycle.join("loop"));
        let err = emit_from(&cycle, &out).expect_err("cycle");
        assert!(err.to_string().contains("symlink cycle"), "{err}");
    }

    fn write(root: &Path, rel: &str, body: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
        fs::write(path, body).expect("write");
    }
}
